<div id="loginp">

	<img src="../image/neo.gif" border="0">
	
	<div>
		<form action="/exelogin" method="post">
		<table>
		  <tr>
		    <td>User Name:</td>
		    <td><input type="text" name="user_name"></td>
		  </tr>
		  <tr>
		    <td>Password:</td>
		    <td><input type="password" name="password"></td>
		  </tr>
		  </table>
		  <tr>	
		<td><input type="submit" name="signin" value="Sign in"></td>
		<td><input type="submit" name="signup" value="Sign up"></td>
		<td><a href="/forgot"><u><i>I forgot my password <i></u></a></td>
		</tr>
		</form>
	</div>
</div>
