<div id="newpasswordp">
<img src="../image/neo.gif" border="0">
<form id="newpassword_form" action="/newpasswordHandler" method="POST">
	<table border="0">
	     
		<tr>
			<td>User Name:</td>
			<td><input type="text" name="usern"></td>
		</tr>
		<tr>
			<td>New Password:</td>
			<td><input type="password" name="passw" id="passw"></td>
		</tr>
		
		
		
	</table>
	<hr color="blue">
<input type="submit" name="change" value="Change">

</form></div>